
[font]
size = 12

[font.normal]
#family = "SF Mono"
family = "Comic Code Ligatures"
[general]
import = [
#    "~/.config/alacritty/themes/themes/smoooooth.toml",
    "~/.config/alacritty/themes/themes/hyper.toml",
]
